### PR TITLE
Fixed: custom image checkbox scaling

### LINKED ISSUE #123: UI: Setting a custom checkbox image does not work well
Trying to set a custom checkbox image results in image-resize and the remember me text being cut off.

checkboxchecked
Testing with this image.

screen shot 2018-05-25 at 12 52 32
Results in this.

### PR DESCRIPTION
**Pull request by aliak00**
Fixes #123

### CODE REVIEW

File: Source/UI/Views/Checkbox.swift [hunk 1]
```diff
@@ -13,11 +13,13 @@ class Checkbox: UIButton, Themeable {
 
     func applyTheme(theme: IdentityUITheme) {
         self.theme = theme
+        self.heightAnchor.constraint(equalToConstant: 26).isActive = true
+        self.widthAnchor.constraint(equalToConstant: 26).isActive = true
         self.setImage(theme.icons.checkedBox, for: .selected)
         self.setImage(theme.icons.uncheckedBox, for: .normal)
         self.setTitle(nil, for: UIControlState.normal)
         self.tintColor = self.stateColor
-        self.translatesAutoresizingMaskIntoConstraints = true
```
Comment (Torsph) [inline Source/UI/Views/Checkbox.swift]: should this still be here? But be set to false?
