### PR TITLE
Fixed: Persist user tokens only after login process is complete

### LINKED ISSUE #102: Cancelling the terms screen keeps user logged in.
When implementing the SDK in my project I get an issue using the login UI. After the password is entered and the continue button is pressed I see the terms screen. When tapping the cancel button (the X in the top right corner) the callback claims the login was cancelled. However, when checking the  `identityManager.currentUser.state` the user seems to be logged in.

### PR DESCRIPTION
**Pull request by aliak00**
Closes #102

### CODE REVIEW

File: Source/Manager/User/User.swift [hunk 1]
```diff
@@ -225,15 +225,22 @@ public class User: UserProtocol {
 
         log(from: self, "new tokens \(newTokens)")
 
-        if let makePersistent = makePersistent {
-            self.isPersistent = makePersistent
+        self.isPersistent = makePersistent ?? self.isPersistent
+
+        let isNewLoggedInUser: Bool
+        if let newAnyUserID = newTokens.anyUserID, newAnyUserID != tokens.old?.anyUserID {
```
Comment (lrossi) [inline Source/Manager/User/User.swift]: Would `let isNewLoggedInUser = newTokens.anyUserID != nil && newTokens.anyUserID != tokens.old?.anyUserID` be clear enough?

File: Source/Manager/User/User.swift [hunk 2]
```diff
@@ -251,17 +258,23 @@ public class User: UserProtocol {
         self.isPersistent = true
     }
 
-    func updateStoredTokens(_ tokens: TokenData?, previousTokens: TokenData?) {
-        // Always clear old tokens
+    private static func updatePersistedTokens(_ tokens: TokenData?, previousTokens: TokenData?) {
```
Comment (lrossi) [inline Source/Manager/User/User.swift]: Since the two operations are now decoupled, could it be clearer to separate this into two methods? (One for storing tokens and another one for clearing).

File: Source/UI/Interactors/OneTimeCodeInteractor.swift [hunk 3]
```diff
@@ -18,8 +18,8 @@ class OneTimeCodeInteractor {
         self.identityManager.resendCode(to: identifier, completion: completion)
     }
 
-    func validate(oneTimeCode: String, for identifier: Identifier, persistUser: Bool, completion: @escaping (Result<User, ClientError>) -> Void) {
-        self.identityManager.validate(oneTimeCode: oneTimeCode, for: identifier, persistUser: persistUser) { [weak self] result in
+    func validate(oneTimeCode: String, for identifier: Identifier, completion: @escaping (Result<User, ClientError>) -> Void) {
+        self.identityManager.validate(oneTimeCode: oneTimeCode, for: identifier, persistUser: false) { [weak self] result in
```
Comment (lrossi) [inline Source/UI/Interactors/OneTimeCodeInteractor.swift]: Should the `persistUser` flag be removed from `IdentityManager`'s method?

Comment (aliak00) [reply Source/UI/Interactors/OneTimeCodeInteractor.swift]: Maybe if we make User.persistCurrentTokens public then? Can think of it in a different PR
