### PR TITLE
Fixed links to GDPR data

### LINKED ISSUE #92: Update the links in Identification and Required Fields link
Links: https://docs.google.com/spreadsheets/d/10kt3MzwG7Gx2vJY3nbVlwYLP7zqXFdaCw425VXY_ZxQ/edit#gid=0

Identification Screen:
What is Schibsted account: S010

Required fields:
adjust your privacy settings at anytime: S007
learn more about Schibsted, data and you: S012

### PR DESCRIPTION
**Pull request by aliak00**

### CODE REVIEW

File: Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift [hunk 1]
```diff
@@ -56,8 +69,31 @@ extension RequiredFieldsViewModel {
...
     }
 
-    var subtext: String {
-        return "RequiredFieldsScreenString.subtext".localized(from: self.localizationBundle)
+    var subtext: NSAttributedString {
+        let text = "RequiredFieldsScreenString.subtext".localized(from: self.localizationBundle)
+        let link0 = "RequiredFieldsScreenString.subtext.link0".localized(from: self.localizationBundle)
+        let link1 = "RequiredFieldsScreenString.subtext.link1".localized(from: self.localizationBundle)
+
+        guard let s007 = URL(string: "https://info.privacy.schibsted.com/" + locale.gdprLanguageCode + "/S007") else {
```
Comment (Torsph) [inline Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift]: What does this numbers mean?

Comment (aliak00) [reply Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift]: Bond.... James Bond

Comment (aliak00) [reply Source/UI/Screens/RequiredFields/RequiredFieldsViewModel.swift]: 🍸
