### PR TITLE
Fixed corner radius theming

### LINKED ISSUE #126: Theming the corner radius of buttons also effects input fields
They shouldn't.

### PR DESCRIPTION
**Pull request by aliak00**
Fixes #126

### CODE REVIEW

File: Source/UI/IdentityUITheme.swift [hunk 1]
```diff
@@ -15,12 +15,19 @@ public struct IdentityUITheme {
...
+    /// Controls spacings and curvatures of views
     public struct Geometry {
-        /// Default curved corner radius of controls
-        public var cornerRadius: CGFloat = 4
-        /// Default spacing between views that form a grouping
+        /// Spacing between views that form a grouping
         public var groupedViewSpacing: CGFloat = 8
+        /// Spacing for in between titles and their associated input fields
+        public var titleViewSpacing: CGFloat = 4
+
```
Comment (Torsph) [inline Source/UI/IdentityUITheme.swift]: Maybe unneeded space?

File: Source/UI/Screens/Error/ErrorViewController.swift [hunk 2]
```diff
@@ -93,6 +93,7 @@ class ErrorViewController: IdentityUIViewController {
     override func viewDidLoad() {
         super.viewDidLoad()
         self.sheetBackgroundView.layer.cornerRadius = self.theme.geometry.cornerRadius
```
Comment (Torsph) [inline Source/UI/Screens/Error/ErrorViewController.swift]: Could maybe be better to use a `UIBezierPath()` if you want smoother corners..
https://twitter.com/nathangitter/status/992842150500069376

Comment (aliak00) [reply Source/UI/Screens/Error/ErrorViewController.swift]: Nice, I switch to bezier everywhere but in some places it was much worse:

image VS image

Becomes a bit more complicated to do if you want to add borders apparently.
